"""baseline schema

Revision ID: 9ee53e33097f
Revises: 
Create Date: 2026-06-15 12:06:12.092413

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee53e33097f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_pipeline_id', sa.BigInteger(), nullable=True),
    sa.Column('old_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('new_pipeline_id', sa.BigInteger(), nullable=True),
    sa.Column('new_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('old_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('new_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_events_deal', 'deal_events', ['deal_id', 'occurred_at'], unique=False)
    op.create_table('email_activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_activity_deal', 'email_activity', ['deal_id', 'conversation_time'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_snapshot',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('deal_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_tasks_owner_status', 'tasks_snapshot', ['owner_id', 'status', 'due_date'], unique=False)
    op.create_table('dashboard_users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('stages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('forecast_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probability', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals_snapshot',
    sa.Column('deal_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('base_currency_amount', sa.Numeric(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('stage_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('rotten_days', sa.Integer(), nullable=True),
    sa.Column('sales_account_id', sa.BigInteger(), nullable=True),
    sa.Column('sales_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cf_project', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cf_floor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cf_sqm_size', sa.Numeric(), nullable=True),
    sa.Column('cf_product_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cf_term', sa.Numeric(), nullable=True),
    sa.Column('cf_start_date', sa.Date(), nullable=True),
    sa.Column('cf_term_end_date', sa.Date(), nullable=True),
    sa.Column('cf_deal_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cf_total_lease_amount', sa.Numeric(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_index('idx_deals_snapshot_owner', 'deals_snapshot', ['owner_id'], unique=False)
    op.create_index('idx_deals_snapshot_pipeline_stage', 'deals_snapshot', ['pipeline_id', 'stage_id'], unique=False)
    op.create_table('pipeline_daily_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(), nullable=True),
    sa.Column('total_base_currency_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('snapshot_date', 'pipeline_id', 'stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_daily_snapshot')
    op.drop_index('idx_deals_snapshot_pipeline_stage', table_name='deals_snapshot')
    op.drop_index('idx_deals_snapshot_owner', table_name='deals_snapshot')
    op.drop_table('deals_snapshot')
    op.drop_table('stages')
    op.drop_table('dashboard_users')
    op.drop_index('idx_tasks_owner_status', table_name='tasks_snapshot')
    op.drop_table('tasks_snapshot')
    op.drop_table('pipelines')
    op.drop_table('owners')
    op.drop_index('idx_email_activity_deal', table_name='email_activity')
    op.drop_table('email_activity')
    op.drop_index('idx_deal_events_deal', table_name='deal_events')
    op.drop_table('deal_events')
    # ### end Alembic commands ###
