"""add_deal_created_at_lost_reason_and_deals_enriched_view

Revision ID: ad205b8f1f36
Revises: f33926afc37b
Create Date: 2026-06-17 16:27:03.128781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad205b8f1f36'
down_revision: Union[str, Sequence[str], None] = 'f33926afc37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Disable timeouts for this session so ALTER TABLE can wait for locks held
    # by the old deployment's deal sync job during rolling restarts.
    op.execute("SET statement_timeout = 0")
    op.execute("SET lock_timeout = 0")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals_snapshot', sa.Column('deal_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals_snapshot', sa.Column('lost_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('deals_snapshot', sa.Column('lost_reason_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE VIEW deals_enriched AS
        SELECT
            d.*,
            s.forecast_type,
            s.probability   AS stage_probability,
            s.name          AS stage_name,
            s.position      AS stage_position,
            p.name          AS pipeline_name,
            p.business_line
        FROM deals_snapshot d
        LEFT JOIN stages    s ON d.stage_id    = s.id
        LEFT JOIN pipelines p ON d.pipeline_id = p.id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS deals_enriched")
    op.drop_column('deals_snapshot', 'lost_reason_id')
    op.drop_column('deals_snapshot', 'lost_reason')
    op.drop_column('deals_snapshot', 'deal_created_at')
    # ### end Alembic commands ###
