"""add_hashed_password_to_dashboard_users

Revision ID: f33926afc37b
Revises: 51283a028465
Create Date: 2026-06-16 10:42:52.284107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33926afc37b'
down_revision: Union[str, Sequence[str], None] = '51283a028465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_users', 'hashed_password')
    # ### end Alembic commands ###
